### ISSUE TITLE
Failed to load a lang-gdscript package grammar in Pulsar

### ISSUE THREAD

**Issue by CyberSkull** [IndicaInkwell/language-gdscript#56]
### Description

After installing the package it immediately throws 2 "Failed to load a lang-gdscript package grammar" errors in Pulsar

### Steps to Reproduce

1. Install the package in Pulsar via the install screen
2. Package throws "Failed to load a lang-gdscript package grammar"

**Expected behavior:**

Package loads

**Actual behavior:**

"Failed to load a lang-gdscript package grammar" is thrown twice.

### Versions

**Pulsar**: 1.118.0 arm64
**Electron**: 12.2.3
**OS**: macOS 14.5
**Thrown From**: [lang-gdscript](https://github.com/PrestonKnopp/language-gdscript) package 6.3.0

### Stack Trace

Failed to load a lang-gdscript package grammar

```
At dlopen(~/.pulsar/packages/lang-gdscript/node_modules/tree-sitter-gdscript/build/Release/tree_sitter_gdscript_binding.node, 0x0001): tried: '~/.pulsar/packages/lang-gdscript/node_modules/tree-sitter-gdscript/build/Release/tree_sitter_gdscript_binding.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS~/.pulsar/packages/lang-gdscript/node_modules/tree-sitter-gdscript/build/Release/tree_sitter_gdscript_binding.node' (no such file), '~/.pulsar/packages/lang-gdscript/node_modules/tree-sitter-gdscript/build/Release/tree_sitter_gdscript_binding.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')) in ~/.pulsar/packages/lang-gdscript/grammars/tree-sitter-gdscript.json

Error: dlopen(~/.pulsar/packages/lang-gdscript/node_modules/tree-sitter-gdscript/build/Release/tree_sitter_gdscript_binding.node, 0x0001): tried: '~/.pulsar/packages/lang-gdscript/node_modules/tree-sitter-gdscript/build/Release/tree_sitter_gdscript_binding.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS~/.pulsar/packages/lang-gdscript/node_modules/tree-sitter-gdscript/build/Release/tree_sitter_gdscript_binding.node' (no such file), '~/.pulsar/packages/lang-gdscript/node_modules/tree-sitter-gdscript/build/Release/tree_sitter_gdscript_binding.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at /packages/lang-gdscript/node_modules/tree-sitter-gdscript/index.js:2:20)
    at /packages/lang-gdscript/node_modules/tree-sitter-gdscript/index.js:11:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:120:30)
    at /app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at /app.asar/src/tree-sitter-grammar.js:61:27)
    at GrammarRegistry.createGrammar (/app.asar/src/grammar-registry.js:761:14)
    at /app.asar/src/grammar-registry.js:738:29
    at parseContents (/app.asar/node_modules/season/lib/cson.js:119:7)
    at /app.asar/node_modules/season/lib/cson.js:226:20
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
  at /packages/lang-gdscript/grammars/tree-sitter-gdscript.json:1:1
```

### Commands

```
     -2:12.8.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -2:09.5.0 editor:consolidate-selections (input.hidden-input)
     -2:09.5.0 core:cancel (input.hidden-input)
     -2:06.8.0 settings-view:view-installed-packages (input.hidden-input)
     -1:59 core:confirm (input.hidden-input)
     -1:57.9.0 core:select-all (input.hidden-input)
     -1:55.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
highlight-selected 0.17.0 
lang-gdscript 6.3.0 
language-arm 2.1.1 
language-powershell 5.0.0 
language-x86-64-assembly 2.3.0 
minimap 4.40.1 
minimap-find-and-replace 5.0.9 
minimap-highlight-selected 4.6.6 
sort-lines 0.19.0 
```

**Comment by CyberSkull** [comment]
This appears to be related to #37.
